language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_install:
   openssl aes-256-cbc -K $encrypted_7b0ee5cfd4e3_key -iv $encrypted_7b0ee5cfd4e3_iv -in .coveralls.yml.enc -out .coveralls.yml -d
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
